import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../../theme/colors";
import { Theme } from "../../../theme/useAppTheme";

export const createStyles = (theme: Theme) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: theme.background,
    },
    container: {
        flex: 1,
        paddingHorizontal: 16,
        backgroundColor: theme.background,
    },
    screenHeader: {
        height: 110,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
    },
    headerGradient: {
        flex: 1,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 52 : 40,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerBackButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: '#FFF',
        fontSize: 20,
        fontWeight: '700',
        marginLeft: 12,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        marginBottom: 8,
    },
    dateDisplay: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.cardBg,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    dateHeaderText: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.text,
        marginRight: 8,
    },
    calendarBtn: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    card: {
        backgroundColor: theme.cardBg,
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 5,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    taskCompany: {
        fontSize: 15,
        fontWeight: '800',
        color: COLORS.primary,
        letterSpacing: 0.3,
    },
    taskStatus: {
        fontSize: 12,
        fontWeight: '700',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        textTransform: 'uppercase',
    },
    statusCompleted: {
        color: '#10B981',
        backgroundColor: 'rgba(16,185,129,0.1)',
    },
    statusInProgress: {
        color: '#F59E0B',
        backgroundColor: 'rgba(245,158,11,0.1)',
    },
    divider: {
        height: 1,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.04)',
        marginVertical: 12,
    },
    taskContainer: {
        marginBottom: 4,
    },
    taskDescription: {
        fontSize: 14,
        color: theme.text,
        fontWeight: '500',
        lineHeight: 20,
    },
    taskMetaRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginTop: 4,
    },
    taskTime: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.textSecondary,
    },
    loader: {
        flex: 1,
        backgroundColor: theme.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fixedButtonContainer: {
        position: 'absolute',
        bottom: 25,
        left: 0,
        right: 0,
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    submitButton: {
        backgroundColor: COLORS.primary,
        height: 56,
        borderRadius: 16,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 10,
    },
    submitButtonText: {
        color: COLORS.white,
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    emptyStateContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 80,
    },
    emptyStateIconWrapper: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: theme.cardBg,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 8,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.02)',
    },
    emptyStateText: {
        textAlign: 'center',
        color: theme.textSecondary,
        fontSize: 16,
        fontWeight: '600',
    },
    editButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 16,
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(96,165,250,0.15)',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    editButtonText: {
        color: '#3B82F6',
        fontWeight: '700',
        marginLeft: 6,
        fontSize: 14,
    },
    // Submit Form Specific
    taskCard: {
        backgroundColor: theme.cardBg,
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
    },
    taskCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    taskCardTitle: {
        fontSize: 17,
        color: theme.text,
        fontWeight: '800',
    },
    formGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        color: theme.textSecondary,
        marginBottom: 8,
        fontWeight: '700',
    },
    input: {
        backgroundColor: theme.inputBg,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 15,
        color: theme.text,
    },
    inlineGroup: {
        flexDirection: 'row',
        gap: 12,
    },
    addTaskButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 16,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: COLORS.primary + '40',
        backgroundColor: COLORS.primary + '08',
        gap: 8,
        marginTop: 8,
    },
    addTaskButtonText: {
        color: COLORS.primary,
        fontSize: 15,
        fontWeight: '700',
    },
    // Quick Date Dropdown
    dropdownOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'flex-start',
        paddingTop: 140,
        paddingHorizontal: 20,
    },
    dropdownMenu: {
        backgroundColor: theme.cardBg,
        borderRadius: 16,
        padding: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
    },
    activeDropdownItem: {
        backgroundColor: COLORS.primary + '15',
    },
    dropdownItemText: {
        fontSize: 15,
        color: theme.text,
        fontWeight: '600',
    },
    activeDropdownItemText: {
        color: COLORS.primary,
        fontWeight: '700',
    },
    dropdownDivider: {
        height: 1,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.03)',
        marginVertical: 4,
    },
    calendarOption: {
        marginTop: 4,
        borderTopWidth: 1,
        borderTopColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
        paddingTop: 8,
    },
});