import { StyleSheet } from "react-native";
import { COLORS } from "../../../theme/colors";

export const createStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
    },
    logoContainer: {
        alignItems: "center",
        marginBottom: 30,
    },
    logo: {
        width: 280,
        height: 100,
    },
    topDecoration: {
        position: 'absolute',
        top: -60,
        right: -60,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: theme.decoration,
        transform: [{ scale: 1.2 }],
    },
    bottomDecoration: {
        position: 'absolute',
        bottom: -80,
        left: -80,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: theme.decoration,
    },
    midDecoration: {
        position: 'absolute',
        top: 200,
        left: -100,
        width: 400,
        height: 400,
        borderRadius: 200,
        backgroundColor: theme.decoration,
        transform: [{ rotate: '45deg' }],
    },
    innerContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    glassCard: {
        borderRadius: 30,
        borderColor: theme.glassCardBorder,
        borderWidth: 1,
        paddingVertical: 35,
        paddingHorizontal: 20,
        width: '100%',
        alignItems: 'center',
        shadowColor: theme.cardShadow,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 15,
        elevation: 8,
    },
    title: {
        fontSize: 28,
        fontWeight: "900",
        color: theme.text,
        marginTop: 10,
        marginBottom: 5,
        textAlign: "center",
        letterSpacing: 0.5,
    },
    subtitle: {
        fontSize: 15,
        color: theme.textSecondary,
        marginBottom: 30,
        textAlign: "center",
        fontWeight: '500',
    },
    inputContainer: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        backgroundColor: theme.inputBg,
        borderRadius: 15,
        paddingHorizontal: 15,
        marginBottom: 15,
        height: 55,
    },
    icon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: theme.text,
        height: '100%',
    },
    eyeIcon: {
        padding: 5,
    },
    button: {
        width: "100%",
        borderRadius: 25,
        overflow: "hidden",
        marginTop: 25,
        marginBottom: 20,
        elevation: 5,
        shadowColor: COLORS.red2,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    buttonGradient: {
        paddingVertical: 16,
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 25,
        width: "100%",
        flexDirection: 'row',
    },
    buttonText: {
        color: COLORS.white,
        fontSize: 17,
        fontWeight: "bold",
        textAlign: "center",
        letterSpacing: 0.5,
        marginRight: 8,
    },
    rememberContainer: {
        width: "100%",
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
        paddingLeft: 5,
    },
    rememberText: {
        color: theme.text,
        marginLeft: 8,
        fontSize: 14,
        fontWeight: '500',
    },
    versionText: {
        position: 'absolute',
        bottom: 20,
        alignSelf: 'center',
        color: theme.textSecondary,
        fontSize: 12,
        opacity: 0.7,
    },
});