import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS } from '../../../theme/colors';

const { height: SCREEN_HEIGHT } = Dimensions.get('screen');

export const createStyles = (theme: any) => StyleSheet.create({
    backdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    header: {
        padding: 16,
        paddingTop: Platform.OS === 'android' ? 16 : 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
        backgroundColor: theme.text === '#FFFFFF' ? '#374151' : '#F3F4F6',
        minWidth: 130,
        height: 48,
    },
    selectedDateText: {
        marginLeft: 8,
        fontSize: 14,
        fontWeight: '600',
        color: theme.text,
    },
    searchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
        paddingHorizontal: 12,
        borderRadius: 12,
        height: 48,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
        backgroundColor: theme.text === '#FFFFFF' ? '#374151' : '#F3F4F6',
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 15,
        color: theme.text,
    },
    listContent: {
        padding: 16,
        paddingBottom: 100,
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 16,
        backgroundColor: theme.text === '#FFFFFF' ? '#1F2937' : '#FFFFFF',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
        marginBottom: 12,
    },
    avatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
    infoContainer: {
        flex: 1,
        marginLeft: 12,
        marginRight: 8,
    },
    name: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.text,
    },
    time: {
        fontSize: 12,
        marginTop: 2,
        color: theme.textSecondary,
    },
    summary: {
        fontSize: 13,
        marginTop: 4,
        lineHeight: 18,
        color: theme.textSecondary,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalContent: {
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        height: SCREEN_HEIGHT * 0.8,
        backgroundColor: theme.cardBg,
        overflow: 'hidden',
    },
    modalHeader: {
        alignItems: 'center',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(0,0,0,0.05)',
        backgroundColor: theme.cardBg,
        zIndex: 1,
    },
    handle: {
        width: 40,
        height: 4,
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 2,
        marginBottom: 10,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.text,
    },
    closeBtn: {
        position: 'absolute',
        right: 20,
        top: 20,
        padding: 4,
    },
    modalBody: {
        padding: 20,
        paddingBottom: 40,
    },
    reportUserHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 12,
    },
    modalName: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.text,
    },
    modalTime: {
        fontSize: 13,
        marginTop: 2,
        color: theme.textSecondary,
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
        marginBottom: 12,
        color: theme.textSecondary,
        textTransform: 'uppercase',
    },
    description: {
        fontSize: 15,
        lineHeight: 22,
        color: theme.text,
        fontStyle: 'italic',
        opacity: 0.7,
    },
    timeDetail: {
        fontSize: 12,
        marginTop: 2,
        color: theme.textSecondary,
        fontWeight: '600',
    },
    taskCard: {
        backgroundColor: theme.background,
        padding: 16,
        borderRadius: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    taskHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    taskCompany: {
        fontSize: 12,
        fontWeight: '800',
        color: COLORS.primary,
        letterSpacing: 0.5,
        flex: 1,
        marginRight: 8,
    },
    statusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    statusText: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    taskDescription: {
        fontSize: 14,
        color: theme.text,
        lineHeight: 22,
        marginBottom: 12,
    },
    taskFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.05)',
    },
    taskDuration: {
        fontSize: 12,
        color: theme.textSecondary,
        marginLeft: 6,
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        alignItems: 'center',
        marginTop: 50,
    },
    emptyText: {
        color: theme.textSecondary,
        marginTop: 10,
        fontSize: 14,
    },
});
