import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../../theme/colors";

const { width, height } = Dimensions.get("window");

export const createStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
    },
    topDecoration: {
        position: 'absolute',
        top: -80,
        right: -60,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: theme.decoration,
        transform: [{ scale: 1.2 }],
    },
    midDecoration: {
        position: 'absolute',
        top: height * 0.3,
        left: -100,
        width: 400,
        height: 400,
        borderRadius: 200,
        backgroundColor: theme.decoration,
        transform: [{ rotate: '45deg' }],
    },
    bottomDecoration: {
        position: 'absolute',
        bottom: -100,
        left: -80,
        width: 350,
        height: 350,
        borderRadius: 175,
        backgroundColor: theme.decoration,
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        zIndex: 1,
    },
    glassCard: {
        width: '100%',
        borderRadius: 35,
        borderWidth: 1.5,
        borderColor: theme.glassCardBorder,
        paddingVertical: 40,
        paddingHorizontal: 24,
        alignItems: 'center',
        shadowColor: theme.cardShadow,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 15,
        elevation: 8,
    },
    imageContainer: {
        marginBottom: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: 320,
        height: 320,
    },
    textContainer: {
        alignItems: 'center',
        marginBottom: 35,
    },
    title: {
        fontSize: 38,
        fontWeight: "900",
        color: theme.text,
        marginBottom: 10,
        textAlign: "center",
        letterSpacing: 1,
        textShadowColor: 'rgba(0,0,0,0.15)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    subtitle: {
        fontSize: 13,
        fontWeight: "700",
        color: theme.textSecondary,
        textAlign: "center",
        marginBottom: 12,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    description: {
        fontSize: 15,
        color: theme.textSecondary,
        textAlign: "center",
        lineHeight: 22,
        fontWeight: '500',
        opacity: 0.8,
    },
    button: {
        width: '100%',
        height: 56,
        borderRadius: 28,
        overflow: 'hidden',
        elevation: 10,
        shadowColor: COLORS.red2,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
    },
    buttonGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        color: COLORS.white,
        fontSize: 17,
        fontWeight: "bold",
        marginRight: 8,
    },
});