import { StyleSheet } from "react-native";
import { COLORS } from "../../../theme/colors";
import { Theme } from "../../../theme/useAppTheme";

export const createStyles = (theme: Theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 14,
        paddingHorizontal: 24,
    },
    weekHeader: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: theme.cardBg,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 4,
    },
    weekText: {
        fontSize: 14,
        fontWeight: "700",
        color: theme.text,
        marginRight: 6,
    },
    navButton: {
        backgroundColor: COLORS.primary,
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
    },
    card: {
        borderRadius: 12,
        backgroundColor: theme.cardBg,
        padding: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    cardTitle: {
        marginLeft: 8,
        fontSize: 16,
        fontWeight: '700',
        color: theme.text,
        flex: 1,
    },
    badge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : '#eef2ff',
    },
    badgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: COLORS.primary,
    },
    cardHeaderGradient: {
        padding: 16,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
    },
    headerTextContainer: {
        marginLeft: 8,
        flex: 1,
    },
    cardTitleWhite: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.white,
    },
    cardDateWhite: {
        fontSize: 12,
        color: COLORS.white,
        opacity: 0.9,
        marginTop: 2,
    },
    cardDate: {
        fontSize: 12,
        color: theme.textSecondary,
        marginTop: 2,
    },
    holidayBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    weekOffBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    badgeTextWhite: {
        fontSize: 12,
        fontWeight: '600',
        color: COLORS.white,
    },
    cardBody: {
        padding: 16,
    },
    holidayContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    holidayTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 8,
        textAlign: 'center',
    },
    holidayText: {
        fontSize: 14,
        color: theme.textSecondary,
        fontStyle: 'italic',
    },
    weekOffContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    weekOffTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 8,
        textAlign: 'center',
    },
    weekOffText: {
        fontSize: 14,
        color: theme.textSecondary,
        fontStyle: 'italic',
    },
    emptyCard: {
        opacity: 0.6,
    },
    shiftHeaderGradient: {
        padding: 16,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
    },
    activeBadge: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    timeRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    timeBox: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    timeBoxContent: {
        marginLeft: 8,
        alignItems: 'center',
    },
    timeLabel: {
        fontSize: 12,
        color: theme.textSecondary,
        fontWeight: '600',
    },
    timeValue: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.text,
        marginTop: 4,
    },
    timeDivider: {
        width: 1,
        height: '80%',
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : '#e5e7eb',
        marginHorizontal: 15,
    },
    durationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : '#e5e7eb',
    },
    durationText: {
        marginLeft: 8,
        fontSize: 14,
        color: theme.textSecondary,
    },
    durationValue: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.text,
    },
    dropdownOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
    },
    dropdownMenu: {
        position: 'absolute',
        top: 70,
        left: 20,
        width: 240,
        backgroundColor: theme.cardBg,
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 10,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderLeftWidth: 3,
        borderLeftColor: 'transparent',
    },
    activeDropdownItem: {
        backgroundColor: COLORS.primary + '10',
        borderLeftColor: COLORS.primary,
    },
    dropdownItemText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.text,
    },
    activeDropdownItemText: {
        color: COLORS.primary,
        fontWeight: '700',
    },
});