import { StyleSheet } from "react-native";
import { COLORS } from "../../theme/colors";

export const createStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.text === '#FFFFFF' ? '#111827' : '#F5F7FA',
    },
    headerBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 240,
        backgroundColor: theme.primary,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        zIndex: 5,
    },
    scrollContent: {
        paddingTop: 260,
        paddingBottom: 110,
    },
    profileHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
        alignItems: "center",
        marginTop: 60,
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    backButton: {
        position: 'absolute',
        top: 60,
        left: 20,
        zIndex: 25,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255,255,255,0.15)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.25)',
    },
    profilePicContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        padding: 4,
        backgroundColor: '#FFFFFF',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 10,
    },
    profilePic: {
        width: '100%',
        height: '100%',
        borderRadius: 46,
    },
    editIconBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#FFFFFF',
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E0E6ED',
    },
    name: {
        marginTop: 12,
        color: '#FFFFFF',
        fontSize: 22,
        fontWeight: "800",
        textAlign: 'center',
        paddingHorizontal: 10,
    },
    email: {
        marginTop: 4,
        color: 'rgba(255,255,255,0.85)',
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 10,
    },
    sectionCard: {
        marginHorizontal: 20,
        marginTop: 10,
        marginBottom: 20,
        backgroundColor: theme.text === '#FFFFFF' ? '#1F2937' : '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 0.5,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 18,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: theme.text === '#FFFFFF' ? '#FFFFFF' : '#374151',
        marginLeft: 10,
    },
    infoGrid: {
        marginTop: 0,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
    },
    infoIconWrapper: {
        width: 38,
        height: 38,
        borderRadius: 10,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    infoContent: {
        flex: 1,
    },
    infoLabel: {
        fontSize: 12,
        color: '#9CA3AF',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    infoValue: {
        fontSize: 15,
        fontWeight: "600",
        color: theme.text === '#FFFFFF' ? '#F3F4F6' : '#111827',
    },
    divider: {
        height: 1,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : '#F3F4F6',
    },
    settingButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
    },
    settingIconWrapper: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    settingText: {
        flex: 1,
        fontSize: 16,
        fontWeight: '600',
        color: theme.text === '#FFFFFF' ? '#FFFFFF' : '#374151',
    },
    switchRoleBtn: {
        marginTop: 15,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(59, 130, 246, 0.1)' : '#EFF6FF',
        borderWidth: 1,
        borderColor: COLORS.primary,
        borderRadius: 15,
        paddingVertical: 12,
        paddingHorizontal: 15,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    switchRoleText: {
        color: COLORS.primary,
        fontWeight: '700',
        fontSize: 15,
        marginLeft: 10,
    },
    logoutButton: {
        marginHorizontal: 20,
        marginTop: 20,
        borderRadius: 25,
        elevation: 5,
        shadowColor: COLORS.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    logoutGradient: {
        width: '100%',
        height: 58,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
        borderRadius: 25,
    },
    logoutText: {
        color: COLORS.white,
        fontSize: 17,
        fontWeight: "bold",
        marginLeft: 10,
    },
    modalOverlay: {
        margin: 0,
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: theme.text === '#FFFFFF' ? '#1F2937' : '#FFFFFF',
        padding: 30,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        alignItems: 'center',
    },
    modalHandle: {
        width: 40,
        height: 4,
        backgroundColor: '#E5E7EB',
        borderRadius: 2,
        marginBottom: 25,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.text === '#FFFFFF' ? '#FFFFFF' : '#111827',
        marginBottom: 10,
    },
    modalMessage: {
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 30,
        lineHeight: 24,
    },
    modalActionButtons: {
        flexDirection: 'row',
        width: '100%',
        gap: 15,
    },
    modalBtn: {
        flex: 1,
        height: 54,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cancelBtn: {
        backgroundColor: '#F3F4F6',
    },
    confirmBtn: {
        backgroundColor: '#EF4444',
    },
    cancelBtnText: {
        color: '#4B5563',
        fontSize: 16,
        fontWeight: '700',
    },
    confirmBtnText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    footer: {
        marginTop: 20,
        marginBottom: 30,
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    versionText: {
        fontSize: 11,
        color: '#9CA3AF',
        opacity: 0.6,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    themeOptionList: {
        width: '100%',
        marginTop: 10,
    },
    themeOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 15,
        borderRadius: 16,
        marginBottom: 12,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.03)' : '#F9FAFB',
        borderWidth: 1.5,
        borderColor: 'transparent',
    },
    themeOptionActive: {
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(59, 130, 246, 0.1)' : '#EFF6FF',
        borderColor: COLORS.primary,
    },
    themeOptionContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    themeOptionIconWrapper: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    themeOptionText: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.7)' : '#4B5563',
    },
    themeOptionTextActive: {
        color: COLORS.primary,
        fontWeight: '700',
    }
});