import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "../../../theme/useAppTheme";
import { COLORS } from "../../../theme/colors";

const { width } = Dimensions.get("window");

export const createStyles = (theme: Theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 100,
    },
    header: {
        padding: 20,
        paddingTop: 10,
    },
    welcomeText: {
        fontSize: 16,
        color: theme.textSecondary,
        fontWeight: "500",
    },
    nameText: {
        fontSize: 24,
        fontWeight: "bold",
        color: theme.text,
        marginTop: 4,
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.cardBg,
        marginHorizontal: 16,
        padding: 12,
        borderRadius: 12,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.glassCardBorder,
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    dateSelectorText: {
        marginLeft: 10,
        fontWeight: '600',
        color: theme.text,
    },
    dateSelectorIconRight: {
        marginLeft: 'auto',
    },
    statsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        marginTop: 10,
    },
    approvalStatsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        marginTop: 10,
        marginBottom: 10,
    },
    statCardMain: {
        width: '100%',
        marginBottom: 16,
        borderRadius: 20,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
    },
    statCardSmall: {
        width: (width - 48) / 2,
        marginBottom: 16,
        borderRadius: 20,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
    },
    cardGradient: {
        padding: 16,
        minHeight: 100,
        justifyContent: "space-between",
    },
    cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    cardIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: "center",
        alignItems: "center",
    },
    cardValue: {
        fontSize: 28,
        fontWeight: "bold",
        color: COLORS.white,
        marginTop: 8,
    },
    cardLabel: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        fontWeight: "600",
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: theme.text,
        marginLeft: 20,
        marginTop: 10,
        marginBottom: 15,
    },
    summaryCard: {
        marginHorizontal: 16,
        padding: 20,
        borderRadius: 20,
        backgroundColor: theme.cardBg,
        borderWidth: 1,
        borderColor: theme.glassCardBorder,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    summaryItem: {
        alignItems: "center",
        flex: 1,
    },
    summaryValue: {
        fontSize: 20,
        fontWeight: "bold",
        color: theme.text,
    },
    summaryLabel: {
        fontSize: 12,
        color: theme.textSecondary,
        marginTop: 4,
    },
    summaryDivider: {
        width: 1,
        height: 30,
        backgroundColor: theme.glassCardBorder,
    },
    chartContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
        position: 'relative',
    },
    chartCenterText: {
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
    },
    chartTotalLabel: {
        fontSize: 12,
        color: theme.textSecondary,
        fontWeight: '600',
    },
    chartTotalValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.text,
    },
    horizontalList: {
        paddingLeft: 16,
        paddingBottom: 20,
    },
    employeeCard: {
        width: 140,
        backgroundColor: theme.cardBg,
        borderRadius: 16,
        padding: 12,
        marginRight: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.glassCardBorder,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    employeeAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginBottom: 8,
        borderWidth: 2,
        borderColor: COLORS.primary,
    },
    employeeName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.text,
        textAlign: 'center',
    },
    employeeCode: {
        fontSize: 12,
        color: theme.textSecondary,
        marginTop: 2,
    },
    employeeLeaveType: {
        fontSize: 12,
        color: COLORS.primary,
        fontWeight: '600',
        marginTop: 2,
    },
    emptyListContainer: {
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'center',
        width: width - 32,
        backgroundColor: theme.cardBg,
        marginHorizontal: 16,
        borderRadius: 16,
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: theme.textSecondary,
    },
    emptyListText: {
        color: theme.textSecondary,
        fontSize: 14,
        fontStyle: 'italic',
    }
});
