import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../../theme/colors";
import { Theme } from "../../../theme/useAppTheme";

export const createStyles = (theme: Theme) => StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 16,
        backgroundColor: theme.background,
    },
    scrollContent: {
        paddingTop: 130,
        paddingBottom: 40,
    },
    screenHeader: {
        height: 110,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
    },
    headerGradient: {
        flex: 1,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 52 : 40,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerBackButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: '#FFF',
        fontSize: 20,
        fontWeight: '700',
        marginLeft: 12,
    },
    fixedButtonContainer: {
        position: 'absolute',
        bottom: 20,
        left: 16,
        right: 16,
        zIndex: 100,
    },
    applyBtn: {
        backgroundColor: COLORS.primary,
        padding: 16,
        borderRadius: 16,
        alignItems: "center",
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    applyText: {
        color: COLORS.white,
        fontSize: 16,
        fontWeight: "700"
    },
    historyButton: {
        alignSelf: "flex-end",
        borderWidth: 1.5,
        borderColor: COLORS.primary,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 12,
        marginTop: 4,
    },
    historyButtonText: {
        color: COLORS.primary,
        fontSize: 13,
        fontWeight: "700",
    },
    timeoffHistorycontainer: {
        flex: 1,
        backgroundColor: theme.background,
    },
    noDataText: {
        textAlign: 'center',
        color: theme.textSecondary,
        fontSize: 16,
        fontStyle: 'italic',
        marginTop: 40,
    },
    cardContainer: {
        flexDirection: "row",
        backgroundColor: theme.cardBg,
        borderRadius: 18,
        marginVertical: 8,
        padding: 14,
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 3,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
    },
    statusIndicator: {
        width: 5,
        borderRadius: 2.5,
    },
    cardContent: {
        flex: 1,
        marginLeft: 14,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    cardTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: theme.text,
    },
    statusBadgeContainer: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    statusBadgeText: {
        color: COLORS.white,
        fontSize: 11,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    infoRow: {
        flexDirection: 'row',
        marginVertical: 3,
    },
    infoLabel: {
        fontWeight: '600',
        color: theme.textSecondary,
        fontSize: 13,
        marginRight: 6,
    },
    infoValue: {
        fontWeight: '600',
        color: theme.text,
        fontSize: 13,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
    },
    statusText: {
        fontSize: 12,
        color: theme.textSecondary,
        fontWeight: '600',
    },
    dateInputBox: {
        backgroundColor: theme.cardBg,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : '#E5E7EB',
        borderRadius: 12,
        padding: 12,
        marginTop: 6,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dateInputText: {
        color: theme.text,
        fontSize: 14,
    },
    approverRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },
    approvedByLabel: {
        fontSize: 13,
        color: theme.textSecondary,
        marginRight: 6,
        fontWeight: '500',
    },
    approvedByName: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.text,
    },
    avatar: {
        width: 26,
        height: 26,
        borderRadius: 13,
        marginHorizontal: 4,
        borderWidth: 1.5,
        borderColor: theme.cardBg,
    },
    statusBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(46, 204, 113, 0.15)' : 'rgba(46, 204, 113, 0.1)',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    formRow: {
        marginBottom: 16,
        zIndex: 1000,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 12,
        color: theme.text,
    },
    emptyBox: {
        alignItems: "center",
        justifyContent: "center",
        padding: 40,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.02)',
        borderRadius: 20,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: theme.textSecondary + '40',
    },
    emptyText: {
        color: theme.textSecondary,
        fontSize: 14,
        fontStyle: "italic"
    },
    listContainer: {
        paddingBottom: 20,
    },
    loader: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    card: {
        backgroundColor: theme.cardBg,
        padding: 16,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 3,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.03)',
    },
    emptyContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        padding: 40,
        marginTop: 40,
    },
    emptySubText: {
        color: theme.textSecondary,
        fontSize: 13,
        textAlign: "center",
        marginTop: 8,
        lineHeight: 20,
        opacity: 0.8,
    },
});