import { StyleSheet } from "react-native";
import { COLORS } from "../../../theme/colors";

export const createStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 14,
        paddingHorizontal: 24,
    },
    weekHeader: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: theme.cardBg,
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 4,
    },
    weekText: {
        fontSize: 14,
        fontWeight: "700",
        color: theme.text,
        marginRight: 6,
    },
    navButton: {
        backgroundColor: COLORS.primary,
        width: 44,
        height: 44,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 6,
    },
    card: {
        backgroundColor: theme.cardBg,
        borderRadius: 24,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.03)',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.05,
        shadowRadius: 16,
        elevation: 8,
        overflow: "hidden",
    },
    cardHeader: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    dateContainer: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    dateIconWrapper: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: 'rgba(255,255,255,0.12)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    dateText: {
        color: COLORS.white,
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0.5,
    },
    arrivalBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: 'rgba(0,128,128,0.2)',
    },
    arrivalText: {
        color: COLORS.white,
        fontSize: 12,
        fontWeight: "800",
        textTransform: 'uppercase',
        marginLeft: 4,
    },
    cardBody: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },
    timeRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    timeBox: {
        flex: 1,
    },
    timeLabelRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    timeLabel: {
        fontSize: 12,
        fontWeight: "800",
        color: theme.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginLeft: 8,
    },
    time: {
        fontSize: 24,
        fontWeight: "900",
        color: theme.text,
        letterSpacing: -0.5,
        marginTop: 2,
    },
    dividerVertical: {
        width: 1,
        height: 48,
        backgroundColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
        marginHorizontal: 8,
    },
    infoGrid: {
        marginTop: 4,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.03)',
    },
    infoLabelGroup: {
        flexDirection: "row",
        alignItems: "center",
    },
    infoIconWrapper: {
        width: 28,
        height: 28,
        borderRadius: 8,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    infoLabel: {
        fontSize: 13,
        fontWeight: "700",
        color: theme.textSecondary,
    },
    infoValue: {
        fontSize: 13,
        fontWeight: "800",
        color: theme.text,
    },
    mapLink: {
        color: '#60A5FA',
        fontSize: 14,
        fontWeight: "900",
        textDecorationLine: 'none',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    holidayContainer: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 32,
    },
    holidayIconWrapper: {
        width: 64,
        height: 64,
        borderRadius: 22,
        backgroundColor: '#FF6B6B15',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    holidayTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: theme.text,
        marginBottom: 6,
        textAlign: "center",
    },
    holidayText: {
        fontSize: 13,
        color: theme.textSecondary,
        textAlign: "center",
        lineHeight: 18,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.7)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        width: "92%",
        height: "75%",
        backgroundColor: theme.cardBg,
        borderRadius: 28,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.08)',
    },
    modalHeader: {
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomWidth: 1,
        borderBottomColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
        backgroundColor: theme.background,
    },
    modalTitle: {
        fontSize: 17,
        fontWeight: "800",
        color: theme.text,
    },
    map: {
        flex: 1,
    },
    closeButton: {
        padding: 18,
        backgroundColor: COLORS.primary,
        alignItems: "center",
    },
    closeButtonText: {
        color: COLORS.white,
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: 0.5,
    },
    dropdownOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'transparent',
    },
    dropdownMenu: {
        position: 'absolute',
        top: 70,
        left: 20,
        width: 240,
        backgroundColor: theme.cardBg,
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 10,
        borderWidth: 1,
        borderColor: theme.text === '#FFFFFF' ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderLeftWidth: 3,
        borderLeftColor: 'transparent',
    },
    activeDropdownItem: {
        backgroundColor: COLORS.primary + '10',
        borderLeftColor: COLORS.primary,
    },
    dropdownItemText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.text,
    },
    activeDropdownItemText: {
        color: COLORS.primary,
        fontWeight: '700',
    },
});